version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  voltdb:
    image: "voltdb/voltdb-community"
    environment:
      - HOST_COUNT=1
    volumes:
      - voltdb:/opt/voltdb
    networks:
      - voltLocalCluster
    ports:
      - 21212:21212
      - 8081:8080

networks:
  voltLocalCluster:

volumes:
  voltdb:
